import { defineConfig } from "astro/config"
import mdx from "@astrojs/mdx"
import sitemap from "@astrojs/sitemap"
import tailwind from "@astrojs/tailwind"
import solidJs from "@astrojs/solid-js"

import remarkLinkCard from "remark-link-card"
import remarkAlert from "remark-github-alerts"
import remarkGfm from "remark-gfm"

// https://astro.build/config
export default defineConfig({
  site: "https://cho-hamanako.info",
  trailingSlash: "always",
  build: {
    inlineStylesheets: "always",
  },
  redirects: {
    // 旧WP記事 → 現行記事（既存ルール。転送先を実URLに修正済み）
    "/2025/10/【初心者必見】浜名湖釣りのルールとマナー完全/": "/blog/guide/beginner/hamanako-fishing-rules-and-manners/",
    "/2024/11/浜名湖周辺にある釣具店をエリア別やおすすめで/": "/blog/shops/",
    "/2025/09/9月の浜名湖投げ釣り五目！キス・カワハギ・ヘダ/": "/blog/casting-gomoku/",
    "/2025/12/winter12-3-lightgame-rockfish/": "/blog/winter-lightgame/",
    "/2024/11/1月の浜名湖で狙える！釣り人おすすめポイントと/": "/blog/1-month/",
    "/2024/09/10月の浜名湖でおすすめの釣りポイント8選/": "/blog/10-month/",
    "/2024/10/11月の浜名湖でおすすめの釣りポイント5選/": "/blog/11-month/",
    "/2024/10/12月の浜名湖でおすすめの釣りポイント/": "/blog/12-month/",
    "/2024/12/2月の浜名湖でおすすめの釣りポイント6選/": "/blog/2-month/",
    "/2025/01/3月の浜名湖でおすすめの釣りポイント10選/": "/blog/3-month/",
    "/2025/02/4月の浜名湖でおすすめの釣りポイント8選/": "/blog/4-month/",
    "/2025/02/5月の浜名湖でおすすめの釣りポイント9選/": "/blog/5-month/",
    "/2025/02/6月の浜名湖でおすすめの釣りポイント9選/": "/blog/6-month/",
    "/2025/02/7月の浜名湖でおすすめの釣りポイント7選/": "/blog/7-month/",
    "/2025/02/8月の浜名湖でおすすめの釣りポイント10選/": "/blog/8-month/",
    "/2024/09/9月の浜名湖でおすすめの釣りポイント6選/": "/blog/9-month/",
    "/hamanako-seasonal-fishing-patterns-guide/": "/blog/seasonal-patterns-guide/",
    "/blog/guide/theory/seasonal-patterns-guide/": "/blog/seasonal-patterns-guide/",
    "/hamanako-fishing-calendar-guide/": "/blog/yearly-fishing-calendar/",
    "/2024/09/家族で安心！浜名湖で車横付け可能な釣り場と設/": "/blog/guide/beginner/family-car-fishing-points/",
    "/2024/11/釣りにめっちゃ役立つ！浜名湖全域の水深を知る/": "/blog/hamana-depth-map-guide/",
    "/blog/guide-2025/": "/blog/tako-kanzen-guide/",
    "/blog/travel/hamanako-rental-fishing-guide/": "/points/araibenten-umiduripark/",

    // 旧WP地名記事 → ポイント記事（クリック順）
    "/2024/08/猪鼻湖（三ヶ日）～奥浜名湖の釣りポイント紹介/": "/points/inahako/",
    "/2024/08/中之島・渚園～表浜名湖の釣りポイント紹介～/": "/points/nagisaen/",
    "/2024/08/舘山寺（内浦湾）～奥浜名湖の釣りポイント紹介/": "/points/kanzanji/",
    "/2024/08/都田川河口～奥浜名湖の釣りポイント紹介～/": "/points/miyakodagawa/",
    "/2024/08/村櫛漁港付近・ガーデンパーク～中浜名湖の釣り/": "/points/murakushi-fishing-port/",
    "/2024/08/瀬戸水道～奥浜名湖の釣りポイント紹介～/": "/points/setosuidou/",
    "/2024/08/新居弁天海釣公園～表浜名湖の釣りポイント～/": "/points/araibenten-umiduripark/",
    "/2024/11/湖南高校周辺～中浜名湖のポイント紹介～/": "/points/konankoukou/",
    "/2024/08/はまゆう大橋～中浜名湖の釣りポイント紹介～/": "/points/hamayu-ohashi/",
    "/2024/08/佐久米海岸～奥浜名湖の釣りポイント紹介～/": "/points/sakumekaigan/",
    "/2024/08/乙女園・サクラマル（弁天島）～表浜名湖の釣り/": "/points/otomeen/",
    "/2024/08/伊目～奥浜名湖の釣りポイント紹介～/": "/points/ime/",
    "/2024/08/鷲津湾周辺～中浜名湖の釣りポイント紹介～/": "/points/washidukou/",
    "/2024/11/浜名湖パークビレッジ付近～表浜名湖の釣りポイ/": "/points/parkvillege/",
    "/2024/08/気賀・寸座～奥浜名湖の釣りポイント紹介～/": "/points/kiga/",
    "/2024/08/庄内湖～奥浜名湖の釣りポイント紹介～/": "/points/syounaiko/",
    "/2024/08/ボートレース浜名湖（浜名湖競艇場）～表浜名湖/": "/points/boatrace-hamanako/",
    "/2024/08/女河浦海水浴場～中浜名湖の釣りポイント紹介～/": "/points/megaura/",
    "/2024/08/松見ヶ浦～中浜名湖の釣りポイント紹介～/": "/points/matsumigaura/",
    "/2025/12/araibenten-12m-winter-fishguide/": "/points/araibenten-umiduripark/",
    "/2025/11/araibenten-11-5select/": "/points/araibenten-umiduripark/",
    "/2024/08/浜名湖の干潟サイトフィッシング～中浜名湖の釣/": "/points/higata-sitefishing/",
    "/2024/11/omote-hamanako-konankoukou/": "/points/konankoukou/",
    "/2024/08/新居町中之郷付近～中浜名湖の釣りポイント紹介/": "/points/arai-nakanogo/",

    // 旧WP記事（魚種・季節ほか） → 現行記事
    "/2024/11/浜名湖シロギス釣りのベストポイント5選！初心者/": "/blog/points-top5/",
    "/2024/11/浜名湖で楽しむアジングの醍醐味：評価の高いポ/": "/blog/ajing-guide/",
    "/2024/10/浜名湖でスズキ（シーバス）釣りのおすすめポイ/": "/blog/seabass-points/",
    "/2024/12/浜名湖でカサゴを釣りたいならここ！おすすめの/": "/blog/kasago-guide/",
    "/2024/11/【初心者必見】冬の浜名湖でカレイを釣る方法！/": "/blog/karei-beginner/",
    "/2024/11/【完全ガイド】浜名湖でハゼ釣りを楽しむ！おす/": "/blog/haze-points/",
    "/2025/10/冬の浜名湖釣りガイド｜初心者向けの釣り方とお/": "/blog/seasonal-patterns-guide/",
    "/2024/11/浜名湖でおすすめのウェーディングポイント10選と/": "/points/wading-points/",
    "/2024/11/浜名湖でサヨリを釣る方法！おすすめのシーズン/": "/blog/sayori-beginner-guide/",
    "/2025/01/3月の浜名湖でおすすめの釣りポイント9選/": "/blog/3-month/",
    "/2024/11/浜名湖でカワハギを釣る方法完全ガイド！釣れる/": "/blog/kawahagi/",
    "/2026/01/hamanako-bachinuke-seabuss/": "/points/bachinuke-fukabori/",
    "/2024/11/浜名湖でメバルを釣る方法～初心者から上級者ま/": "/blog/mebaru-beginner/",
    "/2024/11/浜名湖でサビキ釣りを楽しもう！おすすめのシー/": "/blog/guide/beginner/hamanako-sabiki-best-season/",
    "/2024/12/tactics-fish-kasago/": "/blog/mebaru-kasago/",
    "/2024/10/浜名湖でキビレを釣るおすすめのポイントと方法/": "/blog/kibire-points/",
    "/2025/04/浜名湖でメジナを釣る方法のまとめ！初心者にも/": "/blog/mejina/",
    "/2024/12/釣りに行く直前、浜名湖の状況をライブカメラや/": "/blog/araibenten-live-camera/",
    "/2025/12/seabass-winter-pointtactics/": "/blog/winter-lunker/",
    "/2025/09/9月の浜名湖カレイ釣り開幕！投げ釣りで狙う秋の/": "/blog/hamanako-karei-fishing-season-opener/",
    "/2025/12/hamana-winter-tinu-tactics/": "/blog/winter-tactics/",
    "/2026/02/bachinuke-forecast/": "/blog/bachinuke-forecast/",
    "/2025/01/浜名湖の水温をチェックできる有能なウェブサイ/": "/blog/water-temperature-checking/",
    "/2025/11/hirame-hama-11/": "/blog/november-guide/",
    "/2025/10/【秋の浜名湖】初心者におすすめハゼ・アジ釣り/": "/blog/haze/",
    "/2025/12/hamanako-12season-fishguide/": "/blog/12-month/",
    "/2025/11/hamanako-egging-technic-timepoint/": "/points/eging-fukabori/",
    "/2024/09/今何が釣れる？浜名湖釣魚カレンダーを公開/": "/blog/yearly-fishing-calendar/",
    "/2025/12/hamana-kasago-bignner-winter/": "/blog/winter-kasago/",
    "/2025/10/10月の浜名湖ハゼ釣り完全ガイド！秋の大型ハゼを/": "/blog/haze/",
    "/2025/11/hama11-karei-jsseki/": "/blog/11-november-karei/",
    "/2025/12/hamanako-mebaru-winter-ptactics/": "/blog/winter-lightgame/",
    "/2026/01/hamanako-tsurigushop-choice/": "/blog/shops/",
    "/2026/02/feb-season-forecast/": "/blog/2-month/",
    "/2025/11/hamanako-aorisq-bignner-guide/": "/blog/aori-guide/",
    "/2025/11/beginner-haze-konanch/": "/blog/haze-beginner/",
    "/2025/10/10月の浜名湖投げ釣り入門！カワハギ・ヘダイを狙/": "/blog/casting-gomoku/",
    "/2026/01/winter-mebaru-beginner/": "/blog/mebaru-beginner/",
    "/2026/02/bachinuke-tackle/": "/blog/bachinuke-tackle/",
    "/2025/11/11bansyu-kibire-float/": "/blog/kibire/",
    "/2025/11/bansyu-seabass-area/": "/blog/seabass/",
    "/2024/11/浜名湖の魚を全て釣るには？エサ釣りとルアー釣/": "/blog/seasonal-patterns-guide/",

    // タグ・カテゴリ → 現行記事
    "/category/奥浜名湖/": "/points/oku-hamanako-fishing-points/",
    "/category/表浜名湖/": "/points/omote-hamanako-fishing-points/",
    "/tag/マゴチ/": "/blog/flatfish/",
    "/tag/サヨリ/": "/blog/sayori/",
    "/tag/シーバス/": "/blog/seabass/",

    // Astro移行途中の旧パス → 現行URL（slug フロントマター由来）
    "/blog/guide/method/ajing-guide/": "/blog/ajing-guide/",
    "/blog/target/eging/squid-complete/": "/blog/squid-complete/",
    "/points/oku/pokochan-coast/": "/points/pokochan-coast/",
    "/points/naka/washidukou/": "/points/washidukou/",
    "/blog/season/yearly-fishing-calendar/": "/blog/yearly-fishing-calendar/",
    "/blog/guide/method/night-fishing/": "/blog/night-fishing/",
    "/blog/guide/logistics/parking-toilet-guide/": "/blog/parking-toilet-guide/",
    "/blog/guide/method/hamanako-kayak-fishing/": "/blog/hamanako-kayak-fishing/",
    "/points/naka/gardenpark/": "/points/gardenpark/",
  },
  integrations: [
    mdx({
      remarkPlugins: [remarkGfm, remarkAlert, remarkLinkCard],
    }),
    sitemap({
      filter: (page) => page !== "https://cho-hamanako.info/search/",
    }),
    solidJs(),
    tailwind({ applyBaseStyles: false }),
  ],
})